services:
  hive:
    image: 687253468904.dkr.ecr.us-west-2.amazonaws.com/hive
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    environment:
      ENV: ${ENV}
      MODE: ${MODE}
      NEW_RELIC_KEY: ${NEW_RELIC_KEY}
      ADMIN_SECRET: ${ADMIN_SECRET}
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY}
      USE_MOCK_DATA: "false"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      HASURA_ENDPOINT: ${HASURA_ENDPOINT}